use std::path::{Path, PathBuf};

/// Waterflow Architecture: Plan object for agent creation
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CreateAgentPlan {
    pub target_dir: PathBuf,
    pub agent_name: String,
    pub files: Vec<(PathBuf, String)>,
}

#[allow(dead_code)]
pub struct CreatedAgent {
    pub target_dir: PathBuf,
    pub message: String,
}

// ============================================================================
// GUARD
// ============================================================================

fn guard_agent_name(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    if name.is_empty() {
        return Err("Agent name cannot be empty".into());
    }

    if name.len() > 50 {
        return Err("Agent name too long (max 50 characters)".into());
    }

    let valid = name
        .chars()
        .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-');

    if !valid || name.starts_with('-') || name.ends_with('-') || name.contains("--") {
        return Err(
            "Invalid agent name. Use lowercase letters, numbers, and single hyphens only."
                .into(),
        );
    }

    Ok(())
}

fn guard_target_dir(target_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if target_dir.exists() {
        return Err(format!(
            "Target directory already exists at {}",
            target_dir.display()
        )
        .into());
    }
    Ok(())
}

// ============================================================================
// SHAPE
// ============================================================================

fn shape_target_dir(
    name: &str,
    output_dir: Option<&str>,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let root = match output_dir {
        Some(dir) => PathBuf::from(dir),
        None => crate::cli::create::workspace_root()
            .unwrap_or(default_create_root()?),
    };

    Ok(root.join(format!("opencode-agent-{}", name)))
}

fn default_create_root() -> Result<PathBuf, Box<dyn std::error::Error>> {
    Ok(dirs::data_dir()
        .ok_or("Could not find data directory")?
        .join("skillmine")
        .join("agents"))
}

// ============================================================================
// TRANSFORM
// ============================================================================

fn transform_create_plan(
    name: String,
    output_dir: Option<String>,
) -> Result<CreateAgentPlan, Box<dyn std::error::Error>> {
    guard_agent_name(&name)?;

    let target_dir = shape_target_dir(&name, output_dir.as_deref())?;
    guard_target_dir(&target_dir)?;

    let mut files = Vec::new();
    files.push((
        PathBuf::from("AGENT.md"),
        transform_agent_markdown(&name),
    ));
    files.push((
        PathBuf::from("README.md"),
        transform_agent_readme(&name),
    ));

    Ok(CreateAgentPlan {
        target_dir,
        agent_name: name,
        files,
    })
}

fn transform_agent_markdown(name: &str) -> String {
    format!(
        r#"---
# description is REQUIRED - displayed in @ menu
description: "TODO: Describe this agent's role and when to invoke it"

# mode controls visibility and invocation
# primary  = can be invoked directly with @name
# subagent = can only be called by other agents
# all      = both (default)
mode: subagent

# model override (optional)
# model: anthropic/claude-opus-4-6

# temperature: 0.0=deterministic, 1.0=creative
temperature: 0.1

# steps: max iterations before forced text response
# simple: 5, complex: 10-20
steps: 10

# hidden: true hides from @ autocomplete (useful for subagents)
hidden: false

# permission controls tool access
permission:
  # edit: allow | ask | deny
  edit: ask
  # bash: command-specific rules (last match wins)
  bash:
    "*": ask                    # default: ask for all
    "git status": allow         # safe commands: allow
    "rm *": deny               # dangerous: always deny
  webfetch: ask
  task:
    "*": deny                  # don't spawn sub-agents by default
---

# {name} Agent

## Role

TODO: Define this agent's specialization and persona.

## When to Use

TODO: Describe scenarios where this agent should be invoked.

## Workflow

1. TODO: Step one
2. TODO: Step two
3. TODO: Verification

## Guidelines

- TODO: Specific behaviors
- TODO: Constraints and boundaries

## See Also

- Related agents
- Related skills
"#,
        name = name
    )
}

fn transform_agent_readme(name: &str) -> String {
    format!(
        r#"# {name} Agent

Generated by `skillmine create --type agent`.

## Files

- `AGENT.md` — agent definition with full configuration
- `README.md` — local authoring notes

## Configuration

AGENT.md frontmatter includes:
- `description` - Required, shown in @ menu
- `mode` - primary/subagent/all
- `model` - Optional override
- `temperature` - 0.0 to 1.0
- `steps` - Max iterations
- `hidden` - Hide from @ menu
- `permission` - Tool access control

## Usage

Once synced, invoke with `@{name}` in OpenCode (if mode allows).
"#,
        name = name
    )
}

// ============================================================================
// EFFECT
// ============================================================================

fn effect_execute_create_plan(plan: &CreateAgentPlan) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(&plan.target_dir)?;

    for (relative_path, content) in &plan.files {
        let full_path = plan.target_dir.join(relative_path);
        std::fs::write(&full_path, content)?;
    }

    Ok(())
}

// ============================================================================
// EMIT
// ============================================================================

fn emit_create_success(target_dir: &Path) -> String {
    let path = target_dir.display();
    format!(
        "Created agent at {}\nAutomatically registered and ready to sync.",
        path
    )
}

// ============================================================================
// OBSERVE
// ============================================================================

fn observe_plan_created(plan: &CreateAgentPlan) {
    #[cfg(debug_assertions)]
    eprintln!("[OBSERVE] Agent CreatePlan generated: {:?}", plan.target_dir);
}

fn observe_effect_completed(target_dir: &Path) {
    #[cfg(debug_assertions)]
    eprintln!("[OBSERVE] Agent Effect completed: {:?}", target_dir);
}

// ============================================================================
// PUBLIC API
// ============================================================================

pub(crate) fn create_created_agent(
    name: String,
    output_dir: Option<String>,
) -> Result<CreatedAgent, Box<dyn std::error::Error>> {
    let plan = transform_create_plan(name, output_dir)?;
    observe_plan_created(&plan);

    effect_execute_create_plan(&plan)?;
    observe_effect_completed(&plan.target_dir);

    Ok(CreatedAgent {
        message: emit_create_success(&plan.target_dir),
        target_dir: plan.target_dir,
    })
}

pub async fn create(
    name: String,
    output_dir: Option<String>,
) -> Result<String, Box<dyn std::error::Error>> {
    Ok(create_created_agent(name, output_dir)?.message)
}
