use std::path::{Path, PathBuf};

/// Waterflow Architecture: Plan object for command creation
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CreateCommandPlan {
    pub target_dir: PathBuf,
    pub command_name: String,
    pub files: Vec<(PathBuf, String)>,
}

#[allow(dead_code)]
pub struct CreatedCommand {
    pub target_dir: PathBuf,
    pub message: String,
}

// ============================================================================
// GUARD
// ============================================================================

fn guard_command_name(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    if name.is_empty() {
        return Err("Command name cannot be empty".into());
    }

    if name.len() > 50 {
        return Err("Command name too long (max 50 characters)".into());
    }

    // Commands can have alphanumeric, hyphens, and colons for namespacing
    let valid = name
        .chars()
        .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-' || ch == ':');

    if !valid || name.starts_with('-') || name.ends_with('-') || name.contains("--") {
        return Err(
            "Invalid command name. Use lowercase letters, numbers, single hyphens, or colons only."
                .into(),
        );
    }

    Ok(())
}

fn guard_target_dir(target_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if target_dir.exists() {
        return Err(format!(
            "Target directory already exists at {}",
            target_dir.display()
        )
        .into());
    }
    Ok(())
}

// ============================================================================
// SHAPE
// ============================================================================

fn shape_target_dir(
    name: &str,
    output_dir: Option<&str>,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let root = match output_dir {
        Some(dir) => PathBuf::from(dir),
        None => crate::cli::create::workspace_root()
            .unwrap_or(default_create_root()?),
    };

    Ok(root.join(format!("opencode-command-{}", name)))
}

fn default_create_root() -> Result<PathBuf, Box<dyn std::error::Error>> {
    Ok(dirs::data_dir()
        .ok_or("Could not find data directory")?
        .join("skillmine")
        .join("commands"))
}

// ============================================================================
// TRANSFORM
// ============================================================================

fn transform_create_plan(
    name: String,
    output_dir: Option<String>,
) -> Result<CreateCommandPlan, Box<dyn std::error::Error>> {
    guard_command_name(&name)?;

    let target_dir = shape_target_dir(&name, output_dir.as_deref())?;
    guard_target_dir(&target_dir)?;

    let mut files = Vec::new();
    files.push((
        PathBuf::from("COMMAND.md"),
        transform_command_markdown(&name),
    ));
    files.push((
        PathBuf::from("README.md"),
        transform_command_readme(&name),
    ));

    Ok(CreateCommandPlan {
        target_dir,
        command_name: name,
        files,
    })
}

fn transform_command_markdown(name: &str) -> String {
    format!(
        r#"---
description: "TODO: Describe what this command does"
# agent: reviewer         # Optional: specify which agent executes this
# model: ...              # Optional: override model
# subtask: true           # Optional: run in subagent
---

# /{name}

## Usage

TODO: Describe when and how to use this command.

## Arguments

- `$ARGUMENTS` - All arguments passed to the command
- `$1`, `$2`, etc. - Individual arguments

## Example

Prompt template here. Use variables like:
- $ARGUMENTS for all args
- !`command` for shell output
- @path/to/file for file inclusion
"#,
        name = name
    )
}

fn transform_command_readme(name: &str) -> String {
    format!(
        r#"# {name} Command

Generated by `skillmine create --type command`.

## Files

- `COMMAND.md` — command definition with frontmatter and template
- `README.md` — local authoring notes

## Usage

Once synced, invoke with `/{name}` in OpenCode.
"#,
        name = name
    )
}

// ============================================================================
// EFFECT
// ============================================================================

fn effect_execute_create_plan(plan: &CreateCommandPlan) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(&plan.target_dir)?;

    for (relative_path, content) in &plan.files {
        let full_path = plan.target_dir.join(relative_path);
        std::fs::write(&full_path, content)?;
    }

    Ok(())
}

// ============================================================================
// EMIT
// ============================================================================

fn emit_create_success(target_dir: &Path) -> String {
    let path = target_dir.display();
    format!(
        "Created command at {}\nAutomatically registered and ready to sync.",
        path
    )
}

// ============================================================================
// OBSERVE
// ============================================================================

fn observe_plan_created(plan: &CreateCommandPlan) {
    #[cfg(debug_assertions)]
    eprintln!("[OBSERVE] Command CreatePlan generated: {:?}", plan.target_dir);
}

fn observe_effect_completed(target_dir: &Path) {
    #[cfg(debug_assertions)]
    eprintln!("[OBSERVE] Command Effect completed: {:?}", target_dir);
}

// ============================================================================
// PUBLIC API
// ============================================================================

pub(crate) fn create_created_command(
    name: String,
    output_dir: Option<String>,
) -> Result<CreatedCommand, Box<dyn std::error::Error>> {
    let plan = transform_create_plan(name, output_dir)?;
    observe_plan_created(&plan);

    effect_execute_create_plan(&plan)?;
    observe_effect_completed(&plan.target_dir);

    Ok(CreatedCommand {
        message: emit_create_success(&plan.target_dir),
        target_dir: plan.target_dir,
    })
}

pub async fn create(
    name: String,
    output_dir: Option<String>,
) -> Result<String, Box<dyn std::error::Error>> {
    Ok(create_created_command(name, output_dir)?.message)
}
