use chrono::Utc;
use std::path::{Path, PathBuf};

fn validate_create_skill_name(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    if name.is_empty() {
        return Err("Skill name cannot be empty".into());
    }

    if name.len() > 50 {
        return Err("Skill name too long (max 50 characters)".into());
    }

    let valid = name
        .chars()
        .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-');

    if !valid || name.starts_with('-') || name.ends_with('-') || name.contains("--") {
        return Err(
            "Invalid skill name. Use lowercase letters, numbers, and single hyphens only."
                .into(),
        );
    }

    Ok(())
}

fn create_target_dir(
    name: &str,
    output_dir: Option<&str>,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let root = match output_dir {
        Some(dir) => PathBuf::from(dir),
        None => std::env::current_dir()?,
    };

    Ok(root.join(name))
}

fn create_skill_manifest(name: &str) -> String {
    format!(
        r#"manifest_version = "1.0"

[skill]
name = "{name}"
version = "0.1.0"
description = "Use when creating or iterating on the {name} workflow"
type = "technique"
category = "general"
boundary = "Focused on the {name} workflow and its immediate supporting assets"
maturity = "draft"
last_verified = "{last_verified}"
tags = ["{name}"]
topics = ["general-practice"]
non_goals = ["Managing installed skills"]
"#,
        name = name,
        last_verified = Utc::now().date_naive().format("%Y-%m-%d")
    )
}

fn create_skill_markdown(name: &str) -> String {
    let title = name
        .split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        r#"---
name: {name}
description: Use when creating or iterating on the {name} workflow
---

# {title}

## Overview

Describe what this skill does and the outcome it helps produce.

## When to Use

- Use when you need the {name} workflow.
- Use when a repeatable process would help.

## Steps

1. Describe the first step.
2. Describe the second step.
3. Describe the verification step.

## Common Mistakes

- Being too broad about the boundary.
- Skipping verification or examples.

## See Also

- Related skills or commands.
"#,
        name = name,
        title = title,
    )
}

fn create_skill_readme(name: &str, skill_dir: &Path) -> String {
    format!(
        r#"# {name}

Generated by `skillmine create`.

## Files

- `SKILL.toml` — canonical manifest metadata
- `SKILL.md` — skill instructions and usage guidance
- `README.md` — local authoring notes

## Local lifecycle

1. Edit the scaffolded files in `{path}`
2. Register the local package with `skillmine add {path}`
3. Prepare it with `skillmine install`
4. Expose it with `skillmine sync --target=opencode`
"#,
        name = name,
        path = skill_dir.display(),
    )
}

fn effect_write_created_skill(
    target_dir: &Path,
    name: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(target_dir)?;
    std::fs::write(target_dir.join("SKILL.toml"), create_skill_manifest(name))?;
    std::fs::write(target_dir.join("SKILL.md"), create_skill_markdown(name))?;
    std::fs::write(target_dir.join("README.md"), create_skill_readme(name, target_dir))?;
    Ok(())
}

fn create_success_message(target_dir: &Path) -> String {
    let path = target_dir.display();
    format!(
        "Created skill package at {path}\nNext:\n  1. skillmine add {path}\n  2. skillmine install\n  3. skillmine sync --target=opencode"
    )
}

pub async fn create(
    name: String,
    output_dir: Option<String>,
) -> Result<String, Box<dyn std::error::Error>> {
    validate_create_skill_name(&name)?;
    let target_dir = create_target_dir(&name, output_dir.as_deref())?;

    if target_dir.exists() {
        return Err(format!("Target directory already exists at {}", target_dir.display()).into());
    }

    effect_write_created_skill(&target_dir, &name)?;
    Ok(create_success_message(&target_dir))
}
